import { defaultColors } from 'explorviz-frontend/src/utils/settings/color-schemes';
import {
  SettingLevel,
  VisualizationSettings,
} from 'explorviz-frontend/src/utils/settings/settings-schemas';

export const metricMappingMultipliers = {
  None: 1,
  'Method Count': 10,
  loc: 1,
  LCOM4: 10,
  cyclomatic_complexity: 10,
  cyclomatic_complexity_weighted: 10,
} as const;
export type MetricKey = keyof typeof metricMappingMultipliers;
export const metricKeys = Object.keys(metricMappingMultipliers) as MetricKey[];

export const defaultVizSettings: VisualizationSettings = {
  // Color Settings
  backgroundColor: {
    level: SettingLevel.DEFAULT,
    value: defaultColors.backgroundColor,
    group: 'Colors',
    displayName: 'Background',
    description: '',
    isColorSetting: true,
  },
  classColor: {
    level: SettingLevel.DEFAULT,
    value: defaultColors.classColor,
    group: 'Colors',
    displayName: 'Class',
    description: '',
    isColorSetting: true,
  },
  classTextColor: {
    level: SettingLevel.DEFAULT,
    value: defaultColors.classTextColor,
    group: 'Colors',
    displayName: 'Class Label',
    description: '',
    isColorSetting: true,
  },
  communicationArrowColor: {
    level: SettingLevel.DEFAULT,
    value: defaultColors.communicationArrowColor,
    group: 'Colors',
    displayName: 'Communication Arrow',
    description: '',
    isColorSetting: true,
  },
  communicationColor: {
    level: SettingLevel.DEFAULT,
    value: defaultColors.communicationColor,
    group: 'Colors',
    displayName: 'Communication',
    description: '',
    isColorSetting: true,
  },
  componentEvenColor: {
    level: SettingLevel.DEFAULT,
    value: defaultColors.componentEvenColor,
    group: 'Colors',
    displayName: 'Component Even',
    description: '',
    isColorSetting: true,
  },
  componentOddColor: {
    level: SettingLevel.DEFAULT,
    value: defaultColors.componentOddColor,
    group: 'Colors',
    displayName: 'Component Odd',
    description: '',
    isColorSetting: true,
  },
  componentTextColor: {
    level: SettingLevel.DEFAULT,
    value: defaultColors.componentTextColor,
    group: 'Colors',
    displayName: 'Component Label',
    description: '',
    isColorSetting: true,
  },
  foundationColor: {
    level: SettingLevel.DEFAULT,
    value: defaultColors.foundationColor,
    group: 'Colors',
    displayName: 'Foundation',
    description: '',
    isColorSetting: true,
  },
  foundationTextColor: {
    level: SettingLevel.DEFAULT,
    value: defaultColors.foundationTextColor,
    group: 'Colors',
    displayName: 'Foundation Label',
    description: '',
    isColorSetting: true,
  },
  highlightedEntityColor: {
    level: SettingLevel.DEFAULT,
    value: defaultColors.highlightedEntityColor,
    group: 'Colors',
    displayName: 'Highlighted Entity',
    description: '',
    isColorSetting: true,
  },
  addedComponentColor: {
    level: SettingLevel.EXTENDED,
    value: defaultColors.addedComponentColor,
    group: 'Colors',
    displayName: 'Added Component',
    description: 'Evolution Diff Color',
    isColorSetting: true,
  },
  removedComponentColor: {
    level: SettingLevel.EXTENDED,
    value: defaultColors.removedComponentColor,
    group: 'Colors',
    displayName: 'Removed Component',
    description: 'Evolution Diff Color',
    isColorSetting: true,
  },
  unchangedComponentColor: {
    level: SettingLevel.EXTENDED,
    value: defaultColors.unchangedComponentColor,
    group: 'Colors',
    displayName: 'Unchanged Component',
    description: 'Evolution Diff',
    isColorSetting: true,
  },
  addedClassColor: {
    level: SettingLevel.EXTENDED,
    value: defaultColors.addedClassColor,
    group: 'Colors',
    displayName: 'Added Class',
    description: '',
    isColorSetting: true,
  },
  modifiedClassColor: {
    level: SettingLevel.EXTENDED,
    value: defaultColors.modifiedClassColor,
    group: 'Colors',
    displayName: 'Modified Class',
    description: 'Evolution Diff Color',
    isColorSetting: true,
  },
  removedClassColor: {
    level: SettingLevel.EXTENDED,
    value: defaultColors.removedClassColor,
    group: 'Colors',
    displayName: 'Removed Class',
    description: '',
    isColorSetting: true,
  },
  unchangedClassColor: {
    level: SettingLevel.EXTENDED,
    value: defaultColors.unchangedClassColor,
    group: 'Colors',
    displayName: 'Unchanged Class',
    description: 'Evolution Diff Color',
    isColorSetting: true,
  },
  k8sNodeColor: {
    level: SettingLevel.DEFAULT,
    value: defaultColors.k8sNodeColor,
    group: 'Colors',
    displayName: 'K8s Node',
    description: '',
    isColorSetting: true,
  },
  k8sNamespaceColor: {
    level: SettingLevel.DEFAULT,
    value: defaultColors.k8sNamespaceColor,
    group: 'Colors',
    displayName: 'K8s Namespace',
    description: '',
    isColorSetting: true,
  },
  k8sDeploymentColor: {
    level: SettingLevel.DEFAULT,
    value: defaultColors.k8sDeploymentColor,
    group: 'Colors',
    displayName: 'K8s Deployment',
    description: '',
    isColorSetting: true,
  },
  k8sPodColor: {
    level: SettingLevel.DEFAULT,
    value: defaultColors.k8sPodColor,
    group: 'Colors',
    displayName: 'K8s Pod',
    description: '',
    isColorSetting: true,
  },
  k8sTextColor: {
    level: SettingLevel.DEFAULT,
    value: defaultColors.k8sTextColor,
    group: 'Colors',
    displayName: 'K8s Text',
    description: '',
    isColorSetting: true,
  },
  // Control Settings
  enableGamepadControls: {
    level: SettingLevel.DEFAULT,
    value: true,
    group: 'Controls',
    displayName: 'Enable Gamepad Controls',
    description: 'Toggle gamepad controls for navigation',
    isFlagSetting: true,
  },
  selectedGamepadIndex: {
    level: SettingLevel.EXTENDED,
    value: 0,
    range: { min: 0, max: 10, step: 1 },
    group: 'Controls',
    displayName: 'Selected Gamepad Index',
    description: 'Index of the gamepad to be used for navigation',
    isRangeSetting: true,
  },
  // Heatmap Settings
  heatmapEnabled: {
    level: SettingLevel.DEFAULT,
    value: false,
    group: 'Heatmap',
    displayName: 'Show Heatmap',
    description: 'Toggle visibility of the heatmap',
    isFlagSetting: true,
  },
  // Highlighting Settings
  applyHighlightingOnHover: {
    level: SettingLevel.DEFAULT,
    value: true,
    group: 'Highlighting',
    displayName: 'Only Apply Highlighting Effect on Hover',
    description:
      'Toggle to switch between permanent transparency effect and effect on hover',
    isFlagSetting: true,
  },
  keepHighlightingOnOpenOrClose: {
    level: SettingLevel.DEFAULT,
    value: true,
    group: 'Highlighting',
    displayName: 'Keep Highlighting on Open or Close',
    description:
      'Toggle if highlighting should be reset on double click in application visualization',
    isFlagSetting: true,
  },
  transparencyIntensity: {
    level: SettingLevel.DEFAULT,
    value: 0.1,
    range: { min: 0.0, max: 1.0, step: 0.05 },
    group: 'Highlighting',
    displayName: 'Transparency Intensity in Application Visualization',
    description:
      "Transparency effect intensity ('Enable Transparent Components' must be enabled)",
    isRangeSetting: true,
  },
  enableMultipleHighlighting: {
    level: SettingLevel.DEFAULT,
    value: true,
    group: 'Highlighting',
    displayName: 'Enable Multiple Highlighting',
    description:
      'Toggle if highlighting should be kept on highlighting an unhighlighted component within the same application',
    isFlagSetting: true,
  },
  // Effect Settings
  enableHoverEffects: {
    level: SettingLevel.DEFAULT,
    value: true,
    group: 'Effects',
    displayName: 'Enable Hover Effect',
    description: 'Hover effect (flashing entities) for mouse cursor',
    isFlagSetting: true,
  },
  enableAnimations: {
    level: SettingLevel.DEFAULT,
    value: true,
    group: 'Effects',
    displayName: 'Enable Animations',
    description: 'Toggle animations for opening and closing components',
    isFlagSetting: true,
  },
  castShadows: {
    level: SettingLevel.DEFAULT,
    value: false,
    group: 'Effects',
    displayName: 'Cast Shadows',
    description: 'Enable casting shadows from light (can be expensive)',
    isFlagSetting: true,
  },
  showAllClassLabels: {
    level: SettingLevel.DEFAULT,
    value: true,
    group: 'Effects',
    displayName: 'Show All Class Labels',
    description: 'Shows labels all the time or only when hovered.',
    isFlagSetting: true,
  },
  showOutlines: {
    level: SettingLevel.DEFAULT,
    value: false,
    group: 'Effects',
    displayName: 'Show outlines',
    description: 'Shows black outlines of class meshes',
    isFlagSetting: true,
  },
  // Communication Settings
  commThickness: {
    level: SettingLevel.DEFAULT,
    value: 2.0,
    range: { min: 0.05, max: 5.0, step: 0.05 },
    group: 'Communication',
    displayName: 'Communication Line Thickness',
    description: 'Factor that scales thickness of communication lines',
    isRangeSetting: true,
  },
  commArrowSize: {
    level: SettingLevel.DEFAULT,
    value: 2.0,
    range: { min: 0.0, max: 10.0, step: 0.25 },
    group: 'Communication',
    displayName: 'Arrow Size',
    description:
      'Arrow Size for selected communications in application visualization',
    isRangeSetting: true,
  },
  commArrowOffset: {
    level: SettingLevel.EXTENDED,
    value: 4.0,
    range: { min: -20.0, max: 20.0, step: 0.25 },
    group: 'Communication',
    displayName: 'Arrow Offset',
    description: 'Distance between arrow and communication line',
    isRangeSetting: true,
  },
  curvyCommHeight: {
    level: SettingLevel.DEFAULT,
    value: 1.0,
    range: { min: 0.0, max: 5.0, step: 0.1 },
    group: 'Communication',
    displayName: 'Communication Curviness',
    description:
      'If greater 0.0, communication lines are rendered arc-shaped (Straight lines: 0.0)',
    isRangeSetting: true,
  },
  // Layout settings
  applicationLayoutAlgorithm: {
    level: SettingLevel.DEFAULT,
    value: 'stress',
    options: [
      'box',
      'disco',
      'force',
      'layered',
      'random',
      'rectpacking',
      'sporeOverlap',
      'stress',
    ],
    group: 'Layout',
    displayName: 'Application Layout Algorithm',
    description: 'Determines the layout algorithm for applications',
    isSelectSetting: true,
  },
  packageLayoutAlgorithm: {
    level: SettingLevel.DEFAULT,
    value: 'rectpacking',
    options: [
      'box',
      'disco',
      'force',
      'layered',
      'random',
      'rectpacking',
      'sporeOverlap',
      'stress',
    ],
    group: 'Layout',
    displayName: 'Package Layout Algorithm',
    description: 'Determines the layout algorithm for packages',
    isSelectSetting: true,
  },
  landscapeScalar: {
    level: SettingLevel.EXTENDED,
    value: 0.01,
    range: { min: 0.001, max: 1, step: 0.001 },
    group: 'Layout',
    displayName: 'Landscape Scalar',
    description: 'Scales the whole software landscape.',
    isRangeSetting: true,
  },
  applicationDistance: {
    level: SettingLevel.DEFAULT,
    value: 500.0,
    range: { min: 100, max: 2000, step: 1 },
    group: 'Layout',
    displayName: 'App Distance',
    description: 'Determines a preferred distance between applications',
    isRangeSetting: true,
  },
  applicationAspectRatio: {
    level: SettingLevel.DEFAULT,
    value: 1.0,
    range: { min: 0.25, max: 2.0, step: 0.05 },
    group: 'Layout',
    displayName: 'App Aspect Ratio',
    description: 'Determines a preferred aspect ratio for applications',
    isRangeSetting: true,
  },
  classWidthMetric: {
    level: SettingLevel.DEFAULT,
    value: 'None',
    options: metricKeys,
    group: 'Layout',
    displayName: 'Width Metric',
    description: 'Metric that is mapped to the width of a class.',
    isSelectSetting: true,
  },
  classWidthMultiplier: {
    level: SettingLevel.EXTENDED,
    value: 1.0,
    range: { min: 0, max: 10, step: 0.1 },
    group: 'Layout',
    displayName: 'Width Multiplier',
    description:
      'Multiplier for metric that is mapped to the width of a class.',
    isRangeSetting: true,
  },
  classDepthMetric: {
    level: SettingLevel.DEFAULT,
    value: 'None',
    options: metricKeys,
    group: 'Layout',
    displayName: 'Depth Metric',
    description: 'Metric that is mapped to the depth of a class.',
    isSelectSetting: true,
  },
  classDepthMultiplier: {
    level: SettingLevel.EXTENDED,
    value: 1.0,
    range: { min: 0, max: 10, step: 0.1 },
    group: 'Layout',
    displayName: 'Depth Multiplier',
    description:
      'Multiplier for metric that is mapped to the depth of a class.',
    isRangeSetting: true,
  },
  classHeightMetric: {
    level: SettingLevel.DEFAULT,
    value: 'None',
    options: metricKeys,
    group: 'Layout',
    displayName: 'Height Metric',
    description: 'Metric that is mapped to the height of a class.',
    isSelectSetting: true,
  },
  classHeightMultiplier: {
    level: SettingLevel.EXTENDED,
    value: 1.0,
    range: { min: 0, max: 10, step: 0.1 },
    group: 'Layout',
    displayName: 'Height Multiplier',
    description:
      'Multiplier for metric that is mapped to the height of a class.',
    isRangeSetting: true,
  },
  classFootprint: {
    level: SettingLevel.DEFAULT,
    value: 5.0,
    range: { min: 0.5, max: 20.0, step: 0.5 },
    group: 'Layout',
    displayName: 'Class Footprint',
    description: 'Determines width and depth of classes',
    isRangeSetting: true,
  },
  classMargin: {
    level: SettingLevel.DEFAULT,
    value: 20.0,
    range: { min: 0.0, max: 50.0, step: 1.0 },
    group: 'Layout',
    displayName: 'Class Margin',
    description:
      'Determines distance between classes and to surrounding package',
    isRangeSetting: true,
  },
  classLabelFontSize: {
    level: SettingLevel.EXTENDED,
    value: 2.0,
    range: { min: 0.0, max: 5.0, step: 0.01 },
    group: 'Layout',
    displayName: 'Class Label Font Size',
    description: 'Class Label Font Size',
    isRangeSetting: true,
  },
  classLabelLength: {
    level: SettingLevel.EXTENDED,
    value: 10,
    range: { min: 0, max: 50, step: 1 },
    group: 'Layout',
    displayName: 'Class Label Length',
    description: 'Determines how many letters are shown at maximum',
    isRangeSetting: true,
  },
  classLabelOffset: {
    level: SettingLevel.EXTENDED,
    value: 0.01,
    range: { min: 0, max: 100, step: 0.1 },
    group: 'Layout',
    displayName: 'Class Label Offset',
    description: 'Determines distance between class and its label',
    isRangeSetting: true,
  },
  classLabelOrientation: {
    level: SettingLevel.EXTENDED,
    value: 0.5,
    range: { min: 0.0, max: 6.3, step: 0.01 },
    group: 'Layout',
    displayName: 'Class Label Rotation',
    description: 'Determines rotation of label in radians',
    isRangeSetting: true,
  },
  appLabelMargin: {
    level: SettingLevel.DEFAULT,
    value: 15.0,
    range: { min: 0.0, max: 20.0, step: 0.5 },
    group: 'Layout',
    displayName: 'App Label Margin',
    description:
      'Determines how much space (height) an application label may occupy',
    isRangeSetting: true,
  },
  appMargin: {
    level: SettingLevel.DEFAULT,
    value: 6.0,
    range: { min: 0.0, max: 20.0, step: 0.5 },
    group: 'Layout',
    displayName: 'App Margin',
    description: 'Determines margin of applications',
    isRangeSetting: true,
  },
  packageLabelMargin: {
    level: SettingLevel.DEFAULT,
    value: 13.0,
    range: { min: 0.0, max: 20.0, step: 0.5 },
    group: 'Layout',
    displayName: 'Package Label Margin',
    description:
      'Determines how much space (height) a package label may occupy',
    isRangeSetting: true,
  },
  packageMargin: {
    level: SettingLevel.DEFAULT,
    value: 6.0,
    range: { min: 0.0, max: 20.0, step: 0.5 },
    group: 'Layout',
    displayName: 'Package Margin',
    description: 'Determines margin of packages',
    isRangeSetting: true,
  },
  openedComponentHeight: {
    level: SettingLevel.DEFAULT,
    value: 7.5,
    range: { min: 0.1, max: 100.0, step: 0.1 },
    group: 'Layout',
    displayName: 'Opened Component Height',
    description:
      'Height of opened components (i.e. when contained classes are visible)',
    isRangeSetting: true,
  },
  closedComponentHeight: {
    level: SettingLevel.DEFAULT,
    value: 20,
    range: { min: 0.1, max: 100, step: 0.1 },
    group: 'Layout',
    displayName: 'Closed Component Height',
    description:
      'Height of closed components (i.e. when contained classes are hidden)',
    isRangeSetting: true,
  },
  // Popup settings
  hidePopupDelay: {
    level: SettingLevel.DEFAULT,
    value: 1.0,
    range: { min: 0.0, max: 3.0, step: 0.25 },
    group: 'Popups',
    displayName: 'Hide Popups After',
    description: 'Determines how many seconds popups stay on screen',
    isRangeSetting: true,
  },
  // Camera settings
  cameraNear: {
    level: SettingLevel.EXTENDED,
    value: 0.1,
    range: { min: 0.01, max: 5.0, step: 0.01 },
    group: 'Camera',
    displayName: 'Render Near',
    description: 'Determines near render distance',
    isRangeSetting: true,
  },
  cameraFar: {
    level: SettingLevel.EXTENDED,
    value: 100,
    range: { min: 5.0, max: 500.0, step: 1.0 },
    group: 'Camera',
    displayName: 'Render Far',
    description: 'Determines far render distance',
    isRangeSetting: true,
  },
  cameraFov: {
    level: SettingLevel.EXTENDED,
    value: 75,
    range: { min: 50.0, max: 150.0, step: 5.0 },
    group: 'Camera',
    displayName: 'Field of View',
    description: 'Set field of view for the perspective camera',
    isRangeSetting: true,
  },
  raycastEnabled: {
    level: SettingLevel.DEFAULT,
    value: true,
    group: 'Camera',
    displayName: 'Raycast Enabled',
    description: 'Enables / disables raycasting for interaction.',
    isFlagSetting: true,
  },
  raycastFirstHit: {
    level: SettingLevel.DEFAULT,
    value: true,
    group: 'Camera',
    displayName: 'Raycast First Hit',
    description: 'Only hit the first object with raycaster.',
    isFlagSetting: true,
  },
  raycastNear: {
    level: SettingLevel.EXTENDED,
    value: 0.1,
    range: { min: 0.01, max: 100, step: 0.01 },
    group: 'Camera',
    displayName: 'Raycast Near',
    description:
      'Set near plane for raycasting. Must be smaller than far plane.',
    isRangeSetting: true,
  },
  raycastFar: {
    level: SettingLevel.EXTENDED,
    value: 100,
    range: { min: 0.1, max: 500.0, step: 0.1 },
    group: 'Camera',
    displayName: 'Raycast Far',
    description: 'Far plane for raycasting. Must be larger than near plane.',
    isRangeSetting: true,
  },
  // VR Settings
  showVrButton: {
    level: SettingLevel.DEFAULT,
    value: false,
    group: 'Virtual Reality',
    displayName: 'Show VR Button',
    description: 'Toggle visibility of VR button',
    isFlagSetting: true,
  },
  showVrOnClick: {
    level: SettingLevel.DEFAULT,
    value: true,
    group: 'Virtual Reality',
    displayName: 'Show VR in Browser',
    description: 'Shows the VR room in the browser after joining',
    isFlagSetting: true,
  },

  // Debug Settings
  showExtendedSettings: {
    level: SettingLevel.DEFAULT,
    value: true,
    group: 'Debugging',
    displayName: 'Show Extended Settings',
    description: 'Shows/hides additional settings',
    isFlagSetting: true,
  },
  showFpsCounter: {
    level: SettingLevel.EXTENDED,
    value: false,
    group: 'Debugging',
    displayName: 'Show FPS Counter',
    description: "'Frames Per Second' metrics in visualizations",
    isFlagSetting: true,
  },
  showAxesHelper: {
    level: SettingLevel.EXTENDED,
    value: false,
    group: 'Debugging',
    displayName: 'Show Axes Helper',
    description: 'Visualizes the Three Dimensional Cartesian Coordinate System',
    isFlagSetting: true,
  },
  showLightHelper: {
    level: SettingLevel.EXTENDED,
    value: false,
    group: 'Debugging',
    displayName: 'Show Light Helper',
    description: 'Visualizes the Directional Light',
    isFlagSetting: true,
  },
  showSemanticZoomCenterPoints: {
    level: SettingLevel.EXTENDED,
    value: false,
    type: 'primary',
    group: 'Debugging',
    displayName: 'Semantic Zoom',
    description: 'Show (or hide) center points of semantic zoom',
    buttonText: 'Show Center Points',
    isButtonSetting: true,
  },
  fullscreen: {
    level: SettingLevel.DEFAULT,
    value: false,
    type: 'primary',
    group: 'Debugging',
    displayName: 'Fullscreen',
    description:
      'Enter canvas in fullscreen mode. Press escape key to leave fullscreen.',
    buttonText: 'Enter Fullscreen',
    isButtonSetting: true,
  },
  syncRoomState: {
    level: SettingLevel.DEFAULT,
    value: false,
    type: 'danger',
    group: 'Debugging',
    displayName: 'Synchronize Room State',
    description: 'Sends current state of room to all users, use with caution.',
    buttonText: 'Synchronize',
    isButtonSetting: true,
  },
  resetToDefaults: {
    level: SettingLevel.DEFAULT,
    value: false,
    type: 'danger',
    group: 'Debugging',
    displayName: 'Reset Settings to Default',
    description: 'Reset all settings to default values',
    buttonText: 'Reset',
    isButtonSetting: true,
  },
  // Semantic Zoom Settings
  semanticZoomState: {
    level: SettingLevel.DEFAULT,
    value: false,
    group: 'Semantic Zoom',
    displayName: 'Semantic Zoom',
    description:
      'This switch enables the semantic zoom feature, that hides/shows additional information based on the distance between the user and the object.',
    isFlagSetting: true,
  },
  autoOpenCloseFeature: {
    level: SettingLevel.DEFAULT,
    value: false,
    group: 'Semantic Zoom',
    displayName: 'Auto Open/Close of Components',
    description:
      "Enable or disable the feature to open/close components automatically. Only applies if 'Semantic Zoom' feature is enabled via context menu.",
    isFlagSetting: true,
  },
  useKMeansInsteadOfMeanShift: {
    level: SettingLevel.DEFAULT,
    value: true,
    group: 'Semantic Zoom',
    displayName: 'Use k-Means instead of Shift-Mean',
    description:
      "If on, it uses k-Means clustering with the provided k value below. It works better in combination with 'Auto Open/Close of Components' feature enabled.",
    isFlagSetting: true,
  },
  clusterBasedOnMembers: {
    level: SettingLevel.DEFAULT,
    value: 40.0,
    range: { min: 1.0, max: 100.0, step: 1.0 },
    group: 'Semantic Zoom',
    displayName: 'Relative # of clusters',
    description:
      'It takes a percentage of the number of 3D Objects that are capable of semantic zoom in the scene. It is used as the k in the k-means clustering. If the clustering mode is not k-means, this value is ignored.',
    isRangeSetting: true,
  },
  usePredefinedSet: {
    level: SettingLevel.DEFAULT,
    value: false,
    group: 'Semantic Zoom',
    displayName: 'Use Predefined Set',
    description:
      'If enabled, uses the slider for the predefined sets. Else its customized',
    isFlagSetting: true,
  },
  distancePreSet: {
    level: SettingLevel.DEFAULT,
    value: 1,
    range: { min: 1.0, max: 6.0, step: 1.0 },
    group: 'Semantic Zoom',
    displayName: 'Predefined Zoom Sets',
    description:
      'Use the slider to set predefined values for the 5 levels. 0: Costum. 1: Early/Far, 5: Late/Close',
    isRangeSetting: true,
  },
  distanceLevel1: {
    level: SettingLevel.EXTENDED,
    value: 20,
    range: { min: 1.0, max: 100.0, step: 2.0 },
    group: 'Semantic Zoom',
    displayName: 'Level 1',
    description:
      'Used to trigger different Zoom Levels. Lower value means an early appearence change, while a high value triggers a change if the camera is very close to the object. Should increase with every level towards 100%. An avg of Objects that cover x percent or more of the screen trigger this level.',
    isRangeSetting: true,
  },
  distanceLevel2: {
    level: SettingLevel.EXTENDED,
    value: 65,
    range: { min: 1.0, max: 100.0, step: 2.0 },
    group: 'Semantic Zoom',
    displayName: 'Level 2',
    description:
      'Used to trigger different Zoom Levels. Lower value means an early appearence change, while a high value triggers a change if the camera is very close to the object. Should increase with every level towards 100%. An avg of Objects that cover x percent or more of the screen trigger this level.',
    isRangeSetting: true,
  },
  distanceLevel3: {
    level: SettingLevel.EXTENDED,
    value: 70,
    range: { min: 1.0, max: 100.0, step: 2.0 },
    group: 'Semantic Zoom',
    displayName: 'Level 3',
    description:
      'Used to trigger different Zoom Levels. Lower value means an early appearence change, while a high value triggers a change if the camera is very close to the object. Should increase with every level towards 100%. An avg of Objects that cover x percent or more of the screen trigger this level.',
    isRangeSetting: true,
  },
  distanceLevel4: {
    level: SettingLevel.EXTENDED,
    value: 80,
    range: { min: 1.0, max: 100.0, step: 2.0 },
    group: 'Semantic Zoom',
    displayName: 'Level 4',
    description:
      'Used to trigger different Zoom Levels. Lower value means an early appearence change, while a high value triggers a change if the camera is very close to the object. Should increase with every level towards 100%. An avg of Objects that cover x percent or more of the screen trigger this level.',
    isRangeSetting: true,
  },
  distanceLevel5: {
    level: SettingLevel.EXTENDED,
    value: 90,
    range: { min: 1.0, max: 100.0, step: 2.0 },
    group: 'Semantic Zoom',
    displayName: 'Level 5',
    description:
      'Used to trigger different Zoom Levels. Lower value means an early appearence change, while a high value triggers a change if the camera is very close to the object. Should increase with every level towards 100%. An avg of Objects that cover x percent or more of the screen trigger this level.',
    isRangeSetting: true,
  },
  // Minimap Settings
  minimap: {
    level: SettingLevel.DEFAULT,
    value: false,
    group: 'Minimap',
    displayName: 'Enable Minimap',
    description: 'Toggle visibility of the minimap',
    isFlagSetting: true,
  },
  zoom: {
    level: SettingLevel.DEFAULT,
    value: 1,
    range: { min: 0.1, max: 5, step: 0.05 },
    group: 'Minimap',
    displayName: 'Zoom of Minimap',
    description: 'Set zoom of the minimap',
    isRangeSetting: true,
  },
  useCameraPosition: {
    level: SettingLevel.DEFAULT,
    value: true,
    group: 'Minimap',
    displayName: 'Use Camera Position',
    description:
      'If off, calculate minimap position via intersection of camera with ground plane.',
    isFlagSetting: true,
  },
  layer1: {
    level: SettingLevel.EXTENDED,
    value: true,
    group: 'Minimap',
    displayName: 'Enable foundation visibility',
    description: 'Toggle foundation visibility for the minimap',
    isFlagSetting: true,
  },
  layer2: {
    level: SettingLevel.EXTENDED,
    value: true,
    group: 'Minimap',
    displayName: 'Enable component visibility',
    description: 'Toggle component visibility for the minimap',
    isFlagSetting: true,
  },
  layer3: {
    level: SettingLevel.EXTENDED,
    value: true,
    group: 'Minimap',
    displayName: 'Enable clazz visibility',
    description: 'Toggle clazz visibility for the minimap',
    isFlagSetting: true,
  },
  layer4: {
    level: SettingLevel.EXTENDED,
    value: true,
    group: 'Minimap',
    displayName: 'Enable communication visibility',
    description: 'Toggle communication visibility for the minimap',
    isFlagSetting: true,
  },
  layer6: {
    level: SettingLevel.EXTENDED,
    value: true,
    group: 'Minimap',
    displayName: 'Enable labels visibility',
    description: 'Toggle labels visibility for the minimap',
    isFlagSetting: true,
  },
  layer7: {
    level: SettingLevel.EXTENDED,
    value: true,
    group: 'Minimap',
    displayName: 'Enable visibility of different user-markers',
    description:
      'Toggle the different users position markers visibility for the minimap',
    isFlagSetting: true,
  },
} as const;
