import { defaultColors } from 'explorviz-frontend/src/utils/settings/color-schemes';
import {
  SettingLevel,
  VisualizationSettings,
} from 'explorviz-frontend/src/utils/settings/settings-schemas';

export const metricMappingMultipliers = {
  None: 1,
  'Method Count': 10,
  loc: 1,
  LCOM4: 10,
  cyclomatic_complexity: 10,
  cyclomatic_complexity_weighted: 10,
} as const;
export type MetricKey = keyof typeof metricMappingMultipliers;
export const metricKeys = Object.keys(metricMappingMultipliers) as MetricKey[];
export const MOUSE_ACTIONS = [
  'NONE',
  'ROTATE',
  'TRUCK',
  'SCREEN_PAN',
  'OFFSET',
  'DOLLY',
  'ZOOM',
];

export const defaultVizSettings: VisualizationSettings = {
  // Color Settings
  backgroundColor: {
    level: SettingLevel.DEFAULT,
    value: defaultColors.backgroundColor,
    group: 'Colors',
    displayName: 'Background',
    description: '',
    isColorSetting: true,
  },
  classColor: {
    level: SettingLevel.DEFAULT,
    value: defaultColors.classColor,
    group: 'Colors',
    displayName: 'Class',
    description: '',
    isColorSetting: true,
  },
  classTextColor: {
    level: SettingLevel.DEFAULT,
    value: defaultColors.classTextColor,
    group: 'Colors',
    displayName: 'Class Label',
    description: '',
    isColorSetting: true,
  },
  communicationArrowColor: {
    level: SettingLevel.DEFAULT,
    value: defaultColors.communicationArrowColor,
    group: 'Colors',
    displayName: 'Communication Arrow',
    description: '',
    isColorSetting: true,
  },
  communicationColor: {
    level: SettingLevel.DEFAULT,
    value: defaultColors.communicationColor,
    group: 'Colors',
    displayName: 'Communication',
    description: '',
    isColorSetting: true,
  },
  componentRootLevelColor: {
    level: SettingLevel.DEFAULT,
    value: defaultColors.componentRootLevelColor,
    group: 'Colors',
    displayName: 'Component on Root Level',
    description:
      'Color for components at the root/top level of the component tree',
    isColorSetting: true,
  },
  componentDeepestLevelColor: {
    level: SettingLevel.DEFAULT,
    value: defaultColors.componentDeepestLevelColor,
    group: 'Colors',
    displayName: 'Component on Deepest Level',
    description:
      'Color for components at the deepest level of the component tree',
    isColorSetting: true,
  },
  componentTextColor: {
    level: SettingLevel.DEFAULT,
    value: defaultColors.componentTextColor,
    group: 'Colors',
    displayName: 'Component Label',
    description: '',
    isColorSetting: true,
  },
  foundationColor: {
    level: SettingLevel.DEFAULT,
    value: defaultColors.foundationColor,
    group: 'Colors',
    displayName: 'Foundation',
    description: '',
    isColorSetting: true,
  },
  foundationTextColor: {
    level: SettingLevel.DEFAULT,
    value: defaultColors.foundationTextColor,
    group: 'Colors',
    displayName: 'Foundation Label',
    description: '',
    isColorSetting: true,
  },
  highlightedEntityColor: {
    level: SettingLevel.DEFAULT,
    value: defaultColors.highlightedEntityColor,
    group: 'Colors',
    displayName: 'Highlighted Entity',
    description: '',
    isColorSetting: true,
  },
  addedComponentColor: {
    level: SettingLevel.EXTENDED,
    value: defaultColors.addedComponentColor,
    group: 'Colors',
    displayName: 'Added Component',
    description: 'Evolution Diff Color',
    isColorSetting: true,
  },
  removedComponentColor: {
    level: SettingLevel.EXTENDED,
    value: defaultColors.removedComponentColor,
    group: 'Colors',
    displayName: 'Removed Component',
    description: 'Evolution Diff Color',
    isColorSetting: true,
  },
  unchangedComponentColor: {
    level: SettingLevel.EXTENDED,
    value: defaultColors.unchangedComponentColor,
    group: 'Colors',
    displayName: 'Unchanged Component',
    description: 'Evolution Diff',
    isColorSetting: true,
  },
  addedClassColor: {
    level: SettingLevel.EXTENDED,
    value: defaultColors.addedClassColor,
    group: 'Colors',
    displayName: 'Added Class',
    description: '',
    isColorSetting: true,
  },
  modifiedClassColor: {
    level: SettingLevel.EXTENDED,
    value: defaultColors.modifiedClassColor,
    group: 'Colors',
    displayName: 'Modified Class',
    description: 'Evolution Diff Color',
    isColorSetting: true,
  },
  removedClassColor: {
    level: SettingLevel.EXTENDED,
    value: defaultColors.removedClassColor,
    group: 'Colors',
    displayName: 'Removed Class',
    description: '',
    isColorSetting: true,
  },
  unchangedClassColor: {
    level: SettingLevel.EXTENDED,
    value: defaultColors.unchangedClassColor,
    group: 'Colors',
    displayName: 'Unchanged Class',
    description: 'Evolution Diff Color',
    isColorSetting: true,
  },
  k8sNodeColor: {
    level: SettingLevel.DEFAULT,
    value: defaultColors.k8sNodeColor,
    group: 'Colors',
    displayName: 'K8s Node',
    description: '',
    isColorSetting: true,
  },
  k8sNamespaceColor: {
    level: SettingLevel.DEFAULT,
    value: defaultColors.k8sNamespaceColor,
    group: 'Colors',
    displayName: 'K8s Namespace',
    description: '',
    isColorSetting: true,
  },
  k8sDeploymentColor: {
    level: SettingLevel.DEFAULT,
    value: defaultColors.k8sDeploymentColor,
    group: 'Colors',
    displayName: 'K8s Deployment',
    description: '',
    isColorSetting: true,
  },
  k8sPodColor: {
    level: SettingLevel.DEFAULT,
    value: defaultColors.k8sPodColor,
    group: 'Colors',
    displayName: 'K8s Pod',
    description: '',
    isColorSetting: true,
  },
  k8sTextColor: {
    level: SettingLevel.DEFAULT,
    value: defaultColors.k8sTextColor,
    group: 'Colors',
    displayName: 'K8s Text',
    description: '',
    isColorSetting: true,
  },
  k8sDiagramForegroundColor: {
    level: SettingLevel.DEFAULT,
    value: defaultColors.k8sDiagramForegroundColor,
    group: 'Colors',
    displayName: 'K8s Diagram Foreground',
    description: 'Foreground color for Kubernetes diagram inline SVGs',
    isColorSetting: true,
  },
  k8sDiagramBackgroundColor: {
    level: SettingLevel.DEFAULT,
    value: defaultColors.k8sDiagramBackgroundColor,
    group: 'Colors',
    displayName: 'K8s Diagram Background',
    description: 'Background color for Kubernetes diagram inline SVGs',
    isColorSetting: true,
  },
  k8sDiagramHighlightForegroundColor: { 
    level: SettingLevel.DEFAULT,
    value: defaultColors.k8sDiagramHighlightForegroundColor,
    group: 'Colors',
    displayName: 'K8s Diagram Highlight Foreground',
    description: 'Highlight foreground color for Kubernetes diagram inline SVGs',
    isColorSetting: true,
  },
  k8sDiagramHighlightBackgroundColor: { 
    level: SettingLevel.DEFAULT,
    value: defaultColors.k8sDiagramHighlightBackgroundColor,
    group: 'Colors',
    displayName: 'K8s Diagram Highlight Background',
    description: 'Highlight background color for Kubernetes diagram inline SVGs',
    isColorSetting: true,
  },
  // Control Settings
  leftMouseButtonAction: {
    level: SettingLevel.DEFAULT,
    value: 'SCREEN_PAN',
    options: MOUSE_ACTIONS,
    group: 'Controls',
    displayName: 'Left Mouse Button',
    description: 'Action assigned to the left mouse button',
    isSelectSetting: true,
  },
  middleMouseButtonAction: {
    level: SettingLevel.DEFAULT,
    value: 'NONE',
    options: MOUSE_ACTIONS,
    group: 'Controls',
    displayName: 'Middle Mouse Button',
    description: 'Action assigned to the middle mouse button',
    isSelectSetting: true,
  },
  mouseWheelAction: {
    level: SettingLevel.DEFAULT,
    value: 'DOLLY',
    options: MOUSE_ACTIONS,
    group: 'Controls',
    displayName: 'Mouse Wheel',
    description: 'Action assigned to the mouse wheel',
    isSelectSetting: true,
  },
  rightMouseButtonAction: {
    level: SettingLevel.DEFAULT,
    value: 'ROTATE',
    options: MOUSE_ACTIONS,
    group: 'Controls',
    displayName: 'Right Mouse Button',
    description: 'Action assigned to the right mouse button',
    isSelectSetting: true,
  },
  enableGamepadControls: {
    level: SettingLevel.DEFAULT,
    value: true,
    group: 'Controls',
    displayName: 'Enable Gamepad Controls',
    description: 'Toggle gamepad controls for navigation',
    isFlagSetting: true,
  },
  selectedGamepadIndex: {
    level: SettingLevel.EXTENDED,
    value: 0,
    range: { min: 0, max: 10, step: 1 },
    group: 'Controls',
    displayName: 'Selected Gamepad Index',
    description: 'Index of the gamepad to be used for navigation',
    dependsOn: {
      settingId: 'enableGamepadControls',
      value: true,
    },
    isRangeSetting: true,
  },
  // Heatmap Settings
  heatmapEnabled: {
    level: SettingLevel.DEFAULT,
    value: false,
    group: 'Heatmap',
    displayName: 'Show Heatmap',
    description: 'Toggle visibility of the heatmap',
    isFlagSetting: true,
  },
  // Highlighting Settings
  applyHighlightingOnHover: {
    level: SettingLevel.DEFAULT,
    value: true,
    group: 'Highlighting',
    displayName: 'Only Apply Highlighting Effect on Hover',
    description:
      'Toggle to switch between permanent transparency effect and effect on hover',
    isFlagSetting: true,
  },
  keepHighlightingOnOpenOrClose: {
    level: SettingLevel.DEFAULT,
    value: true,
    group: 'Highlighting',
    displayName: 'Keep Highlighting on Open or Close',
    description:
      'Toggle if highlighting should be reset on double click in application visualization',
    isFlagSetting: true,
  },
  transparencyIntensity: {
    level: SettingLevel.DEFAULT,
    value: 0.1,
    range: { min: 0.0, max: 1.0, step: 0.05 },
    group: 'Highlighting',
    displayName: 'Transparency Intensity in Application Visualization',
    description:
      "Transparency effect intensity ('Enable Transparent Components' must be enabled)",
    isRangeSetting: true,
  },
  enableMultipleHighlighting: {
    level: SettingLevel.DEFAULT,
    value: true,
    group: 'Highlighting',
    displayName: 'Enable Multiple Highlighting',
    description:
      'Toggle if highlighting should be kept on highlighting an unhighlighted component within the same application',
    isFlagSetting: true,
  },
  // Effect Settings
  enableAnimations: {
    level: SettingLevel.DEFAULT,
    value: true,
    group: 'Effects',
    displayName: 'Enable Animations',
    description: 'Toggle animations for opening and closing components',
    isFlagSetting: true,
  },
  animationDuration: {
    level: SettingLevel.DEFAULT,
    value: 0.25,
    range: { min: 0.05, max: 1.0, step: 0.05 },
    group: 'Effects',
    displayName: 'Animation Duration',
    description:
      'Duration of animations in seconds (e.g. opening and closing of components)',
    dependsOn: {
      settingId: 'enableAnimations',
      value: true,
    },
    isRangeSetting: true,
  },
  enableHoverEffects: {
    level: SettingLevel.DEFAULT,
    value: false,
    group: 'Effects',
    displayName: 'Enable Hover Effect',
    description: 'Hover effect (flashing entities) for mouse cursor',
    isFlagSetting: true,
  },
  castShadows: {
    level: SettingLevel.DEFAULT,
    value: false,
    group: 'Effects',
    displayName: 'Cast Shadows',
    description: 'Enable casting shadows from light (can be expensive)',
    isFlagSetting: true,
  },
  showAllClassLabels: {
    level: SettingLevel.DEFAULT,
    value: true,
    group: 'Effects',
    displayName: 'Show All Class Labels',
    description: 'Shows labels all the time or only when hovered.',
    isFlagSetting: true,
  },
  showOutlines: {
    level: SettingLevel.DEFAULT,
    value: false,
    group: 'Effects',
    displayName: 'Show outlines',
    description: 'Shows black outlines of class meshes',
    isFlagSetting: true,
  },
  // Communication Settings
  commThickness: {
    level: SettingLevel.DEFAULT,
    value: 2.0,
    range: { min: 0.05, max: 10.0, step: 0.05 },
    group: 'Communication',
    displayName: 'Communication Line Thickness',
    description: 'Factor that scales thickness of communication lines',
    isRangeSetting: true,
  },
  commArrowSize: {
    level: SettingLevel.DEFAULT,
    value: 2.0,
    range: { min: 0.0, max: 10.0, step: 0.25 },
    group: 'Communication',
    displayName: 'Arrow Size',
    description:
      'Arrow Size for selected communications in application visualization',
    isRangeSetting: true,
  },
  commArrowOffset: {
    level: SettingLevel.EXTENDED,
    value: 4.0,
    range: { min: -20.0, max: 20.0, step: 0.25 },
    group: 'Communication',
    displayName: 'Arrow Offset',
    description: 'Distance between arrow and communication line',
    isRangeSetting: true,
  },
  curvyCommHeight: {
    level: SettingLevel.DEFAULT,
    value: 5.0,
    range: { min: 0.0, max: 25.0, step: 0.1 },
    group: 'Communication',
    displayName: 'Communication Curviness',
    description:
      'If greater 0.0, communication lines are rendered arc-shaped (Straight lines: 0.0)',
    isRangeSetting: true,
  },
  commCurveHeightDependsOnDistance: {
    level: SettingLevel.DEFAULT,
    value: true,
    group: 'Communication',
    displayName: 'Curve Height Depends on Distance',
    description:
      'If enabled, communication curve height is calculated based on the distance between source and target',
    isFlagSetting: true,
  },
  enableEdgeBundling: {
    level: SettingLevel.DEFAULT,
    value: false,
    group: 'Communication',
    displayName: 'Enable Edge Bundling',
    description:
      'Bundle communication lines for better visualization of dense areas',
    isFlagSetting: true,
  },
  bundleStrength: {
    level: SettingLevel.DEFAULT,
    value: 0.3,
    range: { min: 0.0, max: 1.0, step: 0.01 },
    group: 'Communication',
    displayName: 'Bundling Strength',
    description: 'Controls how strongly edges are bundled together',
    dependsOn: {
      settingId: 'enableEdgeBundling',
      value: true,
    },
    isRangeSetting: true,
  },
  compatibilityThreshold: {
    level: SettingLevel.EXTENDED,
    value: 0.6,
    range: { min: 0.0, max: 1.0, step: 0.01 },
    group: 'Communication',
    displayName: 'Compatibility Threshold',
    description: 'Minimum compatibility score for edges to be bundled',
    dependsOn: {
      settingId: 'enableEdgeBundling',
      value: true,
    },
    isRangeSetting: true,
  },
  bundlingIterations: {
    level: SettingLevel.EXTENDED,
    value: 30,
    range: { min: 1, max: 100, step: 1 },
    group: 'Communication',
    displayName: 'Bundling Iterations',
    description:
      'Number of bundling algorithm iterations (higher = better quality)',
    dependsOn: {
      settingId: 'enableEdgeBundling',
      value: true,
    },
    isRangeSetting: true,
  },
  bundlingStepSize: {
    level: SettingLevel.EXTENDED,
    value: 0.1,
    range: { min: 0.01, max: 0.5, step: 0.01 },
    group: 'Communication',
    displayName: 'Bundling Step Size',
    description: 'Step size for bundling algorithm (smaller = smoother)',
    dependsOn: {
      settingId: 'enableEdgeBundling',
      value: true,
    },
    isRangeSetting: true,
  },
  beta: {
    level: SettingLevel.DEFAULT,
    value: 0.8,
    range: { min: 0.0, max: 1.0, step: 0.01 },
    group: 'Communication',
    displayName: '3D-HAP Attraction Power (β)',
    description:
      'Controls the attraction power of hierarchical attraction points (β factor from paper)',
    dependsOn: {
      settingId: 'use3DHAPAlgorithm',
      value: true,
    },
    isRangeSetting: true,
  },
  use3DHAPAlgorithm: {
    level: SettingLevel.DEFAULT,
    value: false,
    group: 'Communication',
    displayName: 'Use 3D-HAP Algorithm',
    description:
      'Enable 3D Hierarchical Edge Bundling algorithm from Caserta paper',
    dependsOn: {
      settingId: 'enableEdgeBundling',
      value: true,
    },
    isFlagSetting: true,
  },
  showHAPTree: {
    level: SettingLevel.DEFAULT,
    value: false,
    group: 'Communication',
    displayName: 'Show HAP Tree',
    description:
      'Debug visualization of HAP (Hierarchical Attraction Points) tree',
    dependsOn: {
      settingId: 'use3DHAPAlgorithm',
      value: true,
    },
    isFlagSetting: true,
  },
  scatterRadius: {
    level: SettingLevel.DEFAULT,
    value: 0.5,
    range: { min: 0.0, max: 3.0, step: 0.05 },
    group: 'Communication',
    displayName: 'Edge Scatter Radius',
    description:
      'Controls how far edges are scattered apart (0 = no scattering)',
    dependsOn: {
      settingId: 'use3DHAPAlgorithm',
      value: true,
    },
    isRangeSetting: true,
  },
  leafPackagesOnly: {
    level: SettingLevel.DEFAULT,
    value: false,
    group: 'Communication',
    displayName: 'Leaf Packages Only',
    description: 'Only create HAPs for packages that contain no sub-packages',
    dependsOn: {
      settingId: 'use3DHAPAlgorithm',
      value: true,
    },
    isFlagSetting: true,
  },
  edgeBundlingStreamline: {
    level: SettingLevel.DEFAULT,
    value: true,
    group: 'Communication',
    displayName: 'Streamline Edge Paths',
    description:
      'Simplify edge paths by keeping only class-level and highest-level HAPs (reduces detours)',
    dependsOn: {
      settingId: 'use3DHAPAlgorithm',
      value: true,
    },
    isFlagSetting: true,
  },
  // Label settings
  appLabelMargin: {
    level: SettingLevel.DEFAULT,
    value: 15.0,
    range: { min: 0.0, max: 20.0, step: 0.5 },
    group: 'Label',
    displayName: 'App Label Margin',
    description:
      'Determines how much space (height) an application label may occupy',
    isRangeSetting: true,
  },
  classLabelFontSize: {
    level: SettingLevel.EXTENDED,
    value: 2.0,
    range: { min: 0.0, max: 5.0, step: 0.01 },
    group: 'Label',
    displayName: 'Class Label Font Size',
    description: 'Class Label Font Size',
    isRangeSetting: true,
  },
  classLabelLength: {
    level: SettingLevel.EXTENDED,
    value: 10,
    range: { min: 0, max: 50, step: 1 },
    group: 'Label',
    displayName: 'Class Label Length',
    description: 'Determines how many letters are shown at maximum',
    isRangeSetting: true,
  },
  classLabelOrientation: {
    level: SettingLevel.EXTENDED,
    value: 0.5,
    range: { min: 0.0, max: 6.3, step: 0.01 },
    group: 'Label',
    displayName: 'Class Label Rotation',
    description: 'Determines rotation of label in radians',
    isRangeSetting: true,
  },
  labelOffset: {
    level: SettingLevel.EXTENDED,
    value: 0.01,
    range: { min: 0, max: 100, step: 0.1 },
    group: 'Label',
    displayName: 'Label Offset',
    description: 'Determines distance between class/component and its label',
    isRangeSetting: true,
  },
  packageLabelMargin: {
    level: SettingLevel.DEFAULT,
    value: 13.0,
    range: { min: 0.0, max: 20.0, step: 0.5 },
    group: 'Label',
    displayName: 'Package Label Margin',
    description:
      'Determines how much space (height) a package label may occupy',
    isRangeSetting: true,
  },
  componentLabelPlacement: {
    level: SettingLevel.DEFAULT,
    value: 'bottom',
    options: ['bottom', 'left', 'right', 'top'],
    group: 'Label',
    displayName: 'Component Label Placement',
    description:
      'Position of application and component labels relative to the application',
    isSelectSetting: true,
  },
  // Layout settings
  applicationLayoutAlgorithm: {
    level: SettingLevel.DEFAULT,
    value: 'stress',
    options: [
      'box',
      'force',
      'layered',
      'random',
      'rectpacking',
      'sporeOverlap',
      'stress',
    ],
    group: 'Layout',
    displayName: 'Application Layout Algorithm',
    description: 'Determines the layout algorithm for applications',
    isSelectSetting: true,
  },
  packageLayoutAlgorithm: {
    level: SettingLevel.DEFAULT,
    value: 'rectpacking',
    options: [
      'box',
      'force',
      'layered',
      'random',
      'rectpacking',
      'sporeOverlap',
      'stress',
    ],
    group: 'Layout',
    displayName: 'Package Layout Algorithm',
    description: 'Determines the layout algorithm for packages',
    isSelectSetting: true,
  },
  classLayoutAlgorithm: {
    level: SettingLevel.DEFAULT,
    value: 'None',
    options: ['None', 'circle', 'spiral'],
    group: 'Layout',
    displayName: 'Class Layout',
    description: 'Layout algorithm for classes within applications',
    isSelectSetting: true,
  },
  spiralCenterOffset: {
    level: SettingLevel.DEFAULT,
    value: 3,
    range: { min: 0, max: 1000, step: 1 },
    group: 'Layout',
    displayName: 'Spiral Center Offset',
    description: 'Offset from center for spiral layout start position',
    dependsOn: {
      settingId: 'classLayoutAlgorithm',
      value: 'spiral',
    },
    isRangeSetting: true,
  },
  spiralGap: {
    level: SettingLevel.DEFAULT,
    value: 1,
    range: { min: 0, max: 10, step: 1 },
    group: 'Layout',
    displayName: 'Spiral Gap',
    description: 'Gap between segments in spiral layout',
    dependsOn: {
      settingId: 'classLayoutAlgorithm',
      value: 'spiral',
    },
    isRangeSetting: true,
  },
  landscapeScalar: {
    level: SettingLevel.EXTENDED,
    value: 0.01,
    range: { min: 0.001, max: 1, step: 0.001 },
    group: 'Layout',
    displayName: 'Landscape Scalar',
    description: 'Scales the whole software landscape.',
    isRangeSetting: true,
  },
  landscapePositionX: {
    level: SettingLevel.EXTENDED,
    value: 0,
    range: { min: -10, max: 10, step: 0.1 },
    group: 'Layout',
    displayName: 'Landscape Position X',
    description: 'Position of the landscape along the X-axis.',
    isRangeSetting: true,
  },
  landscapePositionY: {
    level: SettingLevel.EXTENDED,
    value: 0,
    range: { min: -10, max: 10, step: 0.1 },
    group: 'Layout',
    displayName: 'Landscape Position Y',
    description: 'Position of the landscape along the Y-axis.',
    isRangeSetting: true,
  },
  landscapePositionZ: {
    level: SettingLevel.EXTENDED,
    value: 0,
    range: { min: -10, max: 10, step: 0.1 },
    group: 'Layout',
    displayName: 'Landscape Position Z',
    description: 'Position of the landscape along the Z-axis.',
    isRangeSetting: true,
  },
  landscapeRotationX: {
    level: SettingLevel.EXTENDED,
    value: 0,
    range: { min: -3.14, max: 3.14, step: 0.01 },
    group: 'Layout',
    displayName: 'Landscape Rotation X',
    description: 'Rotation of the landscape around the X-axis in radians.',
    isRangeSetting: true,
  },
  landscapeRotationY: {
    level: SettingLevel.EXTENDED,
    value: 0,
    range: { min: -3.14, max: 3.14, step: 0.01 },
    group: 'Layout',
    displayName: 'Landscape Rotation Y',
    description: 'Rotation of the landscape around the Y-axis in radians.',
    isRangeSetting: true,
  },
  landscapeRotationZ: {
    level: SettingLevel.EXTENDED,
    value: 0,
    range: { min: -3.14, max: 3.14, step: 0.01 },
    group: 'Layout',
    displayName: 'Landscape Rotation Z',
    description: 'Rotation of the landscape around the Z-axis in radians.',
    isRangeSetting: true,
  },
  applicationDistance: {
    level: SettingLevel.DEFAULT,
    value: 500.0,
    range: { min: 100, max: 2000, step: 1 },
    group: 'Layout',
    displayName: 'App Distance',
    description: 'Determines a preferred distance between applications',
    isRangeSetting: true,
  },
  applicationAspectRatio: {
    level: SettingLevel.DEFAULT,
    value: 1.0,
    range: { min: 0.25, max: 2.0, step: 0.05 },
    group: 'Layout',
    displayName: 'App Aspect Ratio',
    description: 'Determines a preferred aspect ratio for applications',
    isRangeSetting: true,
  },
  classWidthMetric: {
    level: SettingLevel.DEFAULT,
    value: 'None',
    options: metricKeys,
    group: 'Layout',
    displayName: 'Width Metric',
    description: 'Metric that is mapped to the width of a class.',
    isSelectSetting: true,
  },
  classWidthMultiplier: {
    level: SettingLevel.EXTENDED,
    value: 1.0,
    range: { min: 0, max: 10, step: 0.1 },
    group: 'Layout',
    displayName: 'Width Multiplier',
    description:
      'Multiplier for metric that is mapped to the width of a class.',
    dependsOn: {
      settingId: 'classWidthMetric',
      notEqual: 'None',
    },
    isRangeSetting: true,
  },
  classDepthMetric: {
    level: SettingLevel.DEFAULT,
    value: 'None',
    options: metricKeys,
    group: 'Layout',
    displayName: 'Depth Metric',
    description: 'Metric that is mapped to the depth of a class.',
    isSelectSetting: true,
  },
  classDepthMultiplier: {
    level: SettingLevel.EXTENDED,
    value: 1.0,
    range: { min: 0, max: 10, step: 0.1 },
    group: 'Layout',
    displayName: 'Depth Multiplier',
    description:
      'Multiplier for metric that is mapped to the depth of a class.',
    dependsOn: {
      settingId: 'classDepthMetric',
      notEqual: 'None',
    },
    isRangeSetting: true,
  },
  classHeightMetric: {
    level: SettingLevel.DEFAULT,
    value: 'None',
    options: metricKeys,
    group: 'Layout',
    displayName: 'Height Metric',
    description: 'Metric that is mapped to the height of a class.',
    isSelectSetting: true,
  },
  classHeightMultiplier: {
    level: SettingLevel.EXTENDED,
    value: 1.0,
    range: { min: 0, max: 10, step: 0.1 },
    group: 'Layout',
    displayName: 'Height Multiplier',
    description:
      'Multiplier for metric that is mapped to the height of a class.',
    dependsOn: {
      settingId: 'classHeightMetric',
      notEqual: 'None',
    },
    isRangeSetting: true,
  },
  classFootprint: {
    level: SettingLevel.DEFAULT,
    value: 5.0,
    range: { min: 0.5, max: 20.0, step: 0.5 },
    group: 'Layout',
    displayName: 'Class Footprint',
    description: 'Determines width and depth of classes',
    isRangeSetting: true,
  },
  classMargin: {
    level: SettingLevel.DEFAULT,
    value: 20.0,
    range: { min: 0.0, max: 50.0, step: 1.0 },
    group: 'Layout',
    displayName: 'Class Margin',
    description:
      'Determines distance between classes and to surrounding package',
    isRangeSetting: true,
  },
  appMargin: {
    level: SettingLevel.DEFAULT,
    value: 6.0,
    range: { min: 0.0, max: 20.0, step: 0.5 },
    group: 'Layout',
    displayName: 'App Margin',
    description: 'Determines margin of applications',
    isRangeSetting: true,
  },
  packageMargin: {
    level: SettingLevel.DEFAULT,
    value: 6.0,
    range: { min: 0.0, max: 20.0, step: 0.5 },
    group: 'Layout',
    displayName: 'Package Margin',
    description: 'Determines margin of packages',
    isRangeSetting: true,
  },
  openedComponentHeight: {
    level: SettingLevel.DEFAULT,
    value: 7.5,
    range: { min: 0.1, max: 100.0, step: 0.1 },
    group: 'Layout',
    displayName: 'Opened Component Height',
    description:
      'Height of opened components (i.e. when contained classes are visible)',
    isRangeSetting: true,
  },
  closedComponentHeight: {
    level: SettingLevel.DEFAULT,
    value: 20,
    range: { min: 0.1, max: 100, step: 0.1 },
    group: 'Layout',
    displayName: 'Closed Component Height',
    description:
      'Height of closed components (i.e. when contained classes are hidden)',
    isRangeSetting: true,
  },
  // Popup settings
  hidePopupDelay: {
    level: SettingLevel.DEFAULT,
    value: 1.0,
    range: { min: 0.0, max: 3.0, step: 0.25 },
    group: 'Popups',
    displayName: 'Hide Popups After',
    description: 'Determines how many seconds popups stay on screen',
    isRangeSetting: true,
  },
  // Semantic Zoom Settings
  enableClustering: {
    level: SettingLevel.DEFAULT,
    value: true,
    group: 'Semantic Zoom',
    displayName: 'Enable Clustering',
    description: 'Enable clustering of classes and packages for semantic zoom',
    isFlagSetting: true,
  },
  clusterCount: {
    level: SettingLevel.DEFAULT,
    value: 0.3,
    range: { min: 0.0, max: 1.0, step: 0.01 },
    group: 'Semantic Zoom',
    displayName: 'Cluster Count',
    description:
      'Number of clusters: 0 = 1 cluster (all entities), 1 = one cluster per entity',
    dependsOn: {
      settingId: 'enableClustering',
      value: true,
    },
    isRangeSetting: true,
  },
  displayClusters: {
    level: SettingLevel.DEFAULT,
    value: false,
    group: 'Semantic Zoom',
    displayName: 'Display Clusters',
    description: 'Visualize cluster centroids as balls in the visualization',
    dependsOn: {
      settingId: 'enableClustering',
      value: true,
    },
    isFlagSetting: true,
  },
  labelDistanceThreshold: {
    level: SettingLevel.DEFAULT,
    value: 5.0,
    range: { min: 0.0, max: 100.0, step: 0.5 },
    group: 'Semantic Zoom',
    displayName: 'Label Distance Threshold',
    description:
      'Maximum distance from camera to cluster centroid for labels to be visible',
    dependsOn: {
      settingId: 'enableClustering',
      value: true,
    },
    isRangeSetting: true,
  },
  distanceUpdateFrequency: {
    level: SettingLevel.DEFAULT,
    value: 10.0,
    range: { min: 1.0, max: 30.0, step: 1.0 },
    group: 'Semantic Zoom',
    displayName: 'Distance Update Frequency',
    description:
      'How often per second the camera distance to cluster centroids is recalculated',
    dependsOn: {
      settingId: 'enableClustering',
      value: true,
    },
    isRangeSetting: true,
  },
  autoOpenCloseComponents: {
    level: SettingLevel.DEFAULT,
    value: false,
    group: 'Semantic Zoom',
    displayName: 'Auto Open/Close Components',
    description:
      'Automatically open components when camera is close to cluster centroid, and close when far away.',
    dependsOn: {
      settingId: 'enableClustering',
      value: true,
    },
    isFlagSetting: true,
  },
  componentOpenCloseDistanceThreshold: {
    level: SettingLevel.DEFAULT,
    value: 15.0,
    range: { min: 0.0, max: 100.0, step: 0.5 },
    group: 'Semantic Zoom',
    displayName: 'Component Open/Close Distance Threshold',
    description:
      'Maximum distance from camera to cluster centroid for components to be automatically opened/closed.',
    dependsOn: {
      settingId: 'autoOpenCloseComponents',
      value: true,
    },
    isRangeSetting: true,
  },
  // Camera settings
  cameraNear: {
    level: SettingLevel.EXTENDED,
    value: 0.1,
    range: { min: 0.01, max: 5.0, step: 0.01 },
    group: 'Camera',
    displayName: 'Render Near',
    description: 'Determines near render distance',
    isRangeSetting: true,
  },
  cameraFar: {
    level: SettingLevel.EXTENDED,
    value: 100,
    range: { min: 5.0, max: 500.0, step: 1.0 },
    group: 'Camera',
    displayName: 'Render Far',
    description: 'Determines far render distance',
    isRangeSetting: true,
  },
  cameraFov: {
    level: SettingLevel.EXTENDED,
    value: 75,
    range: { min: 50.0, max: 150.0, step: 5.0 },
    group: 'Camera',
    displayName: 'Field of View',
    description: 'Set field of view for the perspective camera',
    isRangeSetting: true,
  },
  raycastEnabled: {
    level: SettingLevel.DEFAULT,
    value: true,
    group: 'Camera',
    displayName: 'Raycast Enabled',
    description: 'Enables / disables raycasting for interaction.',
    isFlagSetting: true,
  },
  raycastFirstHit: {
    level: SettingLevel.DEFAULT,
    value: true,
    group: 'Camera',
    displayName: 'Raycast First Hit',
    description: 'Only hit the first object with raycaster.',
    dependsOn: {
      settingId: 'raycastEnabled',
      value: true,
    },
    isFlagSetting: true,
  },
  raycastNear: {
    level: SettingLevel.EXTENDED,
    value: 0.1,
    range: { min: 0.01, max: 100, step: 0.01 },
    group: 'Camera',
    displayName: 'Raycast Near',
    description:
      'Set near plane for raycasting. Must be smaller than far plane.',
    dependsOn: {
      settingId: 'raycastEnabled',
      value: true,
    },
    isRangeSetting: true,
  },
  raycastFar: {
    level: SettingLevel.EXTENDED,
    value: 100,
    range: { min: 0.1, max: 500.0, step: 0.1 },
    group: 'Camera',
    displayName: 'Raycast Far',
    description: 'Far plane for raycasting. Must be larger than near plane.',
    dependsOn: {
      settingId: 'raycastEnabled',
      value: true,
    },
    isRangeSetting: true,
  },
  // VR Settings
  autoEnterVr: {
    level: SettingLevel.DEFAULT,
    value: true,
    group: 'Virtual Reality',
    displayName: 'Automatically Enter VR',
    description: 'Automatically enter VR mode when switch to VR mode',
    isFlagSetting: true,
  },

  // Misc Settings
  showEmbeddedBrowserIcon: {
    level: SettingLevel.DEFAULT,
    value: false,
    group: 'Misc',
    displayName: 'Show Embedded Browser Icons',
    description:
      'Toggle visibility of the embedded browser icons near the code cities',
    isFlagSetting: true,
  },

  // Magnifier Settings
  isMagnifierActive: {
    level: SettingLevel.DEFAULT,
    value: false,
    group: 'Magnifier',
    displayName: 'Enable Magnifier',
    description:
      'Toggle the magnifying glass effect. Can also be toggled with the M key.',
    isFlagSetting: true,
  },
  magnifierZoom: {
    level: SettingLevel.DEFAULT,
    value: 2.0,
    range: { min: 1.0, max: 15.0, step: 0.1 },
    group: 'Magnifier',
    displayName: 'Zoom Factor',
    description: 'Magnification level of the magnifying glass',
    dependsOn: {
      settingId: 'isMagnifierActive',
      value: true,
    },
    isRangeSetting: true,
  },
  magnifierExponent: {
    level: SettingLevel.EXTENDED,
    value: 100.0,
    range: { min: 1.0, max: 100.0, step: 1.0 },
    group: 'Magnifier',
    displayName: 'Glass Shape Exponent',
    description:
      'Controls the shape of the magnifying glass (higher = flatter)',
    dependsOn: {
      settingId: 'isMagnifierActive',
      value: true,
    },
    isRangeSetting: true,
  },
  magnifierRadius: {
    level: SettingLevel.DEFAULT,
    value: 200.0,
    range: { min: 50.0, max: 500.0, step: 10.0 },
    group: 'Magnifier',
    displayName: 'Radius',
    description: 'Size of the magnifying glass in pixels',
    dependsOn: {
      settingId: 'isMagnifierActive',
      value: true,
    },
    isRangeSetting: true,
  },
  magnifierOutlineColor: {
    level: SettingLevel.DEFAULT,
    value: '#cccccc',
    group: 'Magnifier',
    displayName: 'Outline Color',
    description: 'Color of the magnifying glass outline',
    dependsOn: {
      settingId: 'isMagnifierActive',
      value: true,
    },
    isColorSetting: true,
  },
  magnifierOutlineThickness: {
    level: SettingLevel.DEFAULT,
    value: 8.0,
    range: { min: 0.0, max: 20.0, step: 1.0 },
    group: 'Magnifier',
    displayName: 'Outline Thickness',
    description: 'Thickness of the magnifying glass outline (0 = no outline)',
    dependsOn: {
      settingId: 'isMagnifierActive',
      value: true,
    },
    isRangeSetting: true,
  },
  magnifierAntialias: {
    level: SettingLevel.DEFAULT,
    value: true,
    group: 'Magnifier',
    displayName: 'Enable Anti-aliasing',
    description: 'Apply FXAA anti-aliasing for smoother edges',
    dependsOn: {
      settingId: 'isMagnifierActive',
      value: true,
    },
    isFlagSetting: true,
  },

  // Debug Settings
  showExtendedSettings: {
    level: SettingLevel.DEFAULT,
    value: true,
    group: 'Debugging',
    displayName: 'Show Extended Settings',
    description: 'Shows/hides additional settings',
    isFlagSetting: true,
  },
  showFpsCounter: {
    level: SettingLevel.EXTENDED,
    value: false,
    group: 'Debugging',
    displayName: 'Show FPS Counter',
    description: "'Frames Per Second' metrics in visualizations",
    isFlagSetting: true,
  },
  showAxesHelper: {
    level: SettingLevel.EXTENDED,
    value: false,
    group: 'Debugging',
    displayName: 'Show Axes Helper',
    description: 'Visualizes the Three Dimensional Cartesian Coordinate System',
    isFlagSetting: true,
  },
  showLightHelper: {
    level: SettingLevel.EXTENDED,
    value: false,
    group: 'Debugging',
    displayName: 'Show Light Helper',
    description: 'Visualizes the Directional Light',
    isFlagSetting: true,
  },
  entityOpacity: {
    level: SettingLevel.EXTENDED,
    value: 1.0,
    range: { min: 0.0, max: 1.0, step: 0.01 },
    group: 'Debugging',
    displayName: 'Entity Opacity',
    description:
      'Controls the opacity of city foundation, city districts, and code buildings',
    isRangeSetting: true,
  },
  fullscreen: {
    level: SettingLevel.DEFAULT,
    value: false,
    type: 'primary',
    group: 'Debugging',
    displayName: 'Fullscreen',
    description:
      'Enter canvas in fullscreen mode. Press escape key to leave fullscreen.',
    buttonText: 'Enter Fullscreen',
    isButtonSetting: true,
  },
  syncRoomState: {
    level: SettingLevel.DEFAULT,
    value: false,
    type: 'danger',
    group: 'Debugging',
    displayName: 'Synchronize Room State',
    description: 'Sends current state of room to all users, use with caution.',
    buttonText: 'Synchronize',
    isButtonSetting: true,
  },
  clearTraceData: {
    level: SettingLevel.EXTENDED,
    value: false,
    type: 'danger',
    group: 'Debugging',
    displayName: 'Clear Trace Data',
    description:
      'Removes all trace and span data from the database for the current landscape token. This action cannot be undone!',
    buttonText: 'Clear Trace Data',
    isButtonSetting: true,
  },
  resetToDefaults: {
    level: SettingLevel.DEFAULT,
    value: false,
    type: 'danger',
    group: 'Debugging',
    displayName: 'Reset Settings to Default',
    description: 'Reset all settings to default values',
    buttonText: 'Reset',
    isButtonSetting: true,
  },
  // Minimap Settings
  isMinimapEnabled: {
    level: SettingLevel.DEFAULT,
    value: false,
    group: 'Minimap',
    displayName: 'Enable Minimap',
    description: 'Toggle visibility of the minimap',
    isFlagSetting: true,
  },
  minimapCorner: {
    level: SettingLevel.DEFAULT,
    value: 'top-left',
    options: [
      'top-left',
      'top-middle',
      'top-right',
      'middle-right',
      'bottom-right',
      'bottom-middle',
      'bottom-left',
      'middle-left',
    ],
    group: 'Minimap',
    displayName: 'Minimap Corner',
    description: 'Corner in which the minimap should be placed',
    dependsOn: {
      settingId: 'isMinimapEnabled',
      value: true,
    },
    isSelectSetting: true,
  },
  minimapZoom: {
    level: SettingLevel.DEFAULT,
    value: 0.5,
    range: { min: 0, max: 5, step: 0.05 },
    group: 'Minimap',
    displayName: 'Zoom of Minimap',
    description: 'Set zoom of the minimap',
    dependsOn: {
      settingId: 'isMinimapEnabled',
      value: true,
    },
    isRangeSetting: true,
  },
  minimapShape: {
    level: SettingLevel.DEFAULT,
    value: 'round',
    options: ['rectangle', 'round'],
    group: 'Minimap',
    displayName: 'Minimap Shape',
    description: 'Shape of the minimap',
    dependsOn: {
      settingId: 'isMinimapEnabled',
      value: true,
    },
    isSelectSetting: true,
  },
  minimapWidth: {
    level: SettingLevel.DEFAULT,
    value: 300,
    range: { min: 50, max: 1000, step: 5 },
    group: 'Minimap',
    displayName: 'Minimap Width',
    description: 'Width of the minimap',
    dependsOn: {
      settingId: 'isMinimapEnabled',
      value: true,
    },
    isRangeSetting: true,
  },
  minimapHeight: {
    level: SettingLevel.DEFAULT,
    value: 300,
    range: { min: 50, max: 1000, step: 5 },
    group: 'Minimap',
    displayName: 'Minimap Height',
    description: 'Height of the minimap',
    dependsOn: {
      settingId: 'isMinimapEnabled',
      value: true,
    },
    isRangeSetting: true,
  },
  minimapMarginX: {
    level: SettingLevel.DEFAULT,
    value: 35,
    range: { min: 0, max: 100, step: 1 },
    group: 'Minimap',
    displayName: 'Margin Padding X',
    description: 'Margin in x-direction to the edge of the viewport',
    dependsOn: {
      settingId: 'isMinimapEnabled',
      value: true,
    },
    isRangeSetting: true,
  },
  minimapMarginY: {
    level: SettingLevel.DEFAULT,
    value: 35,
    range: { min: 0, max: 100, step: 1 },
    group: 'Minimap',
    displayName: 'Minimap Margin Y',
    description: 'Margin in y-direction to the edge of the viewport',
    dependsOn: {
      settingId: 'isMinimapEnabled',
      value: true,
    },
    isRangeSetting: true,
  },
  minimapBgColor: {
    level: SettingLevel.DEFAULT,
    value: '#d3d3d3',
    group: 'Minimap',
    displayName: 'Minimap Background Color',
    description: 'Set background color of the minimap',
    dependsOn: {
      settingId: 'isMinimapEnabled',
      value: true,
    },
    isColorSetting: true,
  },
  minimapMode: {
    level: SettingLevel.DEFAULT,
    value: 'camera',
    options: ['camera', 'target', 'landscape'],
    group: 'Minimap',
    displayName: 'Minimap Tracking Mode',
    description:
      'Determines what the minimap tracks (Camera, Target, or fixed Landscape)',
    dependsOn: {
      settingId: 'isMinimapEnabled',
      value: true,
    },
    isSelectSetting: true,
  },
  minimapRotate: {
    level: SettingLevel.DEFAULT,
    value: true,
    group: 'Minimap',
    displayName: 'Rotate Minimap',
    description:
      'If on, the minimap rotates with the main camera. If off, it stays north-oriented.',
    dependsOn: {
      settingId: 'isMinimapEnabled',
      value: true,
    },
    isFlagSetting: true,
  },
  layer1: {
    level: SettingLevel.EXTENDED,
    value: true,
    group: 'Minimap',
    displayName: 'Enable foundation visibility',
    description: 'Toggle foundation visibility for the minimap',
    dependsOn: {
      settingId: 'isMinimapEnabled',
      value: true,
    },
    isFlagSetting: true,
  },
  layer2: {
    level: SettingLevel.EXTENDED,
    value: true,
    group: 'Minimap',
    displayName: 'Enable component visibility',
    description: 'Toggle component visibility for the minimap',
    dependsOn: {
      settingId: 'isMinimapEnabled',
      value: true,
    },
    isFlagSetting: true,
  },
  layer3: {
    level: SettingLevel.EXTENDED,
    value: true,
    group: 'Minimap',
    displayName: 'Enable clazz visibility',
    description: 'Toggle clazz visibility for the minimap',
    dependsOn: {
      settingId: 'isMinimapEnabled',
      value: true,
    },
    isFlagSetting: true,
  },
  layer4: {
    level: SettingLevel.EXTENDED,
    value: false,
    group: 'Minimap',
    displayName: 'Enable communication visibility',
    description: 'Toggle communication visibility for the minimap',
    dependsOn: {
      settingId: 'isMinimapEnabled',
      value: true,
    },
    isFlagSetting: true,
  },
  layer6: {
    level: SettingLevel.EXTENDED,
    value: false,
    group: 'Minimap',
    displayName: 'Enable labels visibility',
    description: 'Toggle labels visibility for the minimap',
    dependsOn: {
      settingId: 'isMinimapEnabled',
      value: true,
    },
    isFlagSetting: true,
  },
  layer7: {
    level: SettingLevel.EXTENDED,
    value: true,
    group: 'Minimap',
    displayName: 'Enable visibility of different user-markers',
    description:
      'Toggle the different users position markers visibility for the minimap',
    dependsOn: {
      settingId: 'isMinimapEnabled',
      value: true,
    },
    isFlagSetting: true,
  },
} as const;
