version: '3.5'
services:
  demo-supplier:
    container_name: explorviz-demo-supplier
    image: explorviz/demo-supplier
    ports:
      - ${LANDSCAPE_PORT}:8082
      - ${TRACE_PORT}:8083
      - ${USER_PORT}:8084

networks:
  default:
    name: explorviz
