version: '3.5'
services:
  collaboration-service:
    container_name: collaboration-service
    image: explorviz/collaboration-service-jvm:latest
    ports:
      - ${COLLABORATION_PORT}:4444
    environment:
      - EXPLORVIZ_LOG_LVL=DEBUG

  demo-supplier:
    container_name: explorviz-demo-supplier
    image: explorviz/demo-supplier
    ports:
      - ${LANDSCAPE_PORT}:8082
      - ${TRACE_PORT}:8083
      - ${USER_PORT}:8084

networks:
  default:
    name: explorviz
