services:

  demo-supplier:
    container_name: explorviz-demo-supplier
    image: explorviz/demo-supplier
    ports:
      - ${USER_PORT}:8084
      - ${PERSISTENCE_PORT}:8085

  kubediagrams:
    build:
      context: ..
      dockerfile: .dev/Dockerfile.kubediagrams-api
    container_name: kubediagrams-api
    volumes:
      - ..:/work
    working_dir: /work
    ports:
      - "9123:9123"
    command: ["node", "server/index.js"]


networks:
  default:
    name: explorviz
