FROM node:20-alpine

# install system deps
RUN apk add --no-cache \
    bash \
    curl \
    git \
    python3 \
    py3-pip \
    pipx

ENV PATH="/root/.local/bin:${PATH}"

RUN pipx install KubeDiagrams

RUN curl -L https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl \
    -o /usr/local/bin/kubectl && \
    chmod +x /usr/local/bin/kubectl

WORKDIR /work
