services:

  demo-supplier:
    container_name: explorviz-demo-supplier
    image: explorviz/demo-supplier
    ports:
      - ${SPAN_PORT}:8083
      - ${USER_PORT}:8084
      - ${CODE_PORT}:9999 # not used anymore

networks:
  default:
    name: explorviz
